Add PostgreSQL JDBC driver
oVirt/ovirt-dependencies pull request #9
Opened 2022-04-27 07:17 UTC by mwperina

Adds PostgreSQL JDBC driver due to recent regression by PostgreSQL JDBC
drivers > 42.2.10

Bug-Url: https://bugzilla.redhat.com/2077794
Signed-off-by: Martin Perina <mperina@redhat.com>

2022-04-27 07:30 UTC, dupondje commented on ovirt-dependencies.spec.in
> +Provides:   bundled(posttgresql-jdbc) = @POSTGRESQL_JDBC_VERSION@
Typo? posttgresql

2022-04-27 07:38 UTC, sandrobonazzola requested changes
See @dupondje comment

2022-04-27 07:46 UTC, arso requested changes
Looks good except a typo in spec 'posttgresql' . 
I was only a bit surprised that xmvn did not complain about missing parent pom ... perhaps it's already shipped with different package?

EDIT: actually it did complain.  
Unable to resolve parent POM org.postgresql:pgjdbc-core-parent:pom:1.1

These 2 parent poms need to be added under %install and above postgresqljdbc:
%mvn_artifact dependencies/org/postgresql/pgjdbc-versions/1.1/pgjdbc-versions-1.1.pom
%mvn_artifact dependencies/org/postgresql/pgjdbc-core-parent/1.1/pgjdbc-core-parent-1.1.pom

2022-04-27 07:46 UTC, arso commented on ovirt-dependencies.spec.in
> +Provides:   bundled(posttgresql-jdbc) = @POSTGRESQL_JDBC_VERSION@
+1

2022-04-27 08:13 UTC, arso commented on ovirt-dependencies.spec.in
> +%mvn_artifact dependencies/org/postgresql/postgresql/@POSTGRESQL_JDBC_VERSION@/postgresql-@POSTGRESQL_JDBC_VERSION@.pom dependencies/org/postgresql/postgresql/@PPOSTGRESQL_JDBC_VERSION@/postgresql-@P
typo: @PPOSTGRESQL_JDBC_VERSION@   -> @POSTGRESQL_JDBC_VERSION@

2022-04-27 08:15 UTC, arso commented
I have pushed updates (I've made them for the review anyway)

2022-04-27 08:16 UTC, arso commented on ovirt-dependencies.spec.in
> +%mvn_artifact dependencies/org/postgresql/postgresql/@POSTGRESQL_JDBC_VERSION@/postgresql-@POSTGRESQL_JDBC_VERSION@.pom dependencies/org/postgresql/postgresql/@PPOSTGRESQL_JDBC_VERSION@/postgresql-@P
Fixed

2022-04-27 08:17 UTC, arso commented on ovirt-dependencies.spec.in
> +Provides:   bundled(posttgresql-jdbc) = @POSTGRESQL_JDBC_VERSION@
fixed

2022-04-27 08:20 UTC, arso approved these changes

2022-04-28 05:23 UTC, sandrobonazzola approved these changes
LGTM

2022-04-28 06:18 UTC, mwperina commented
I'd wait with merging till Monday, we should know if this workaround is needed or we will have better solution

2022-05-10 12:57 UTC, mwperina commented
Closing in favor of https://github.com/oVirt/ovirt-engine/pull/322 and https://github.com/oVirt/ovirt-dependencies/pull/10

2022-05-10 12:57 UTC, closed without merging